### PR TITLE
persons mentioned in text

### PR DESCRIPTION
**Pull request by elespdn**
Added list of mentioned person in text-page, using the same mechanism of pages (asynchronous because need IRI from text)

### CODE REVIEW

**Comment by elespdn** [comment]
Closes #10

**Comment by gfoo** [comment]
Also don't forget to retrieve all `Page` and `Person` resources in text view, so far you are just getting the first page of results. (maybe you should create a separate issue for that?)

**Comment by elespdn** [comment]
> Also don't forget to retrieve all `Page` and `Person` resources in text view, so far you are just getting the first page of results. (maybe you should create a separate issue for that?)

New issue created

**Comment by elespdn** [comment]
>     * remove console logs
Done

> the orResourceLink directive in person view does not work anymore with my data (http://localhost:4200/persons/http%253A%252F%252Frdfh.ch%252F0112%252FljwLu9JJTkylpWyxf60WoQ), but I probably do not have the last xsl to work with the a[class="resourceLink"] selector
Yes, it works with the last XSL

> I don't have any pages related to texts ?
No, I add them through http post in Postman after the import, because cannot save data without mapping and data with mapping creates duplicates.

**Pull request merged**
