### PR TITLE
Sort results

### PR DESCRIPTION
**Pull request by elespdn**
Sort the results of full text query. Basic mechanism is there, unless there is better way.

Still to do:
- add other classes
- better rendering of titles

Attention: bugs may be caused by permissions (for example, on the property `:establishedTextHasTitle`).

### CODE REVIEW

**Comment by elespdn** [comment]
**Issue**: it keeps the results when new search is done. Before these changes, it did not do that ..

**Comment by elespdn** [comment]
> Issue: it keeps the results when new search is done. Before these changes, it did not do that ..

solved in 458265b , unless there is a more elegant way

**Comment by gfoo** [comment]
- Prefer `getResources` of IRIs instead of several `getResource` of an IRI to retrieve all your persons and texts.

It means that you have to post filter your result to extract IRIs of a particular class) : 
```typescript
// will return an array of IRI of persons from result resources
const personIRIs = this.resources.filter(r => r.resourceClassLabel == "Person").map(r => r.id);

// call new service this.dataService.getPErsons(personIRIs).sub... etc.
```
A new service getPersons(iri: string[]): 
``` 
getPersons(iris: string[]): Observable<Person[]> {
    return this.knoraApiConnection.v2.res
      .getResources(iris)
      .pipe(
        map((readResources: ReadResource[]) => readResources.map(r => this.readRes2Person(r)))
      );
  }
``` 

- From UI point of view I understand that you want to show a lot of informations in your result page but it is not really efficient to call Knora API a lot. A *go between* way is to show labels and if persons are loaded, then replace label by person name etc. I will show you how to do that.

- you should probably manage *next page* button now before to have more complicated stuffs

- you could also make a  `knoraApiConnection.v2.search.doFulltextSearch` per class, in the parameter `IFulltextSearchParams` there the attribute `limitToResourceClass`

**Comment by elespdn** [comment]
> you should probably manage next page button now before to have more complicated stuffs

I would like to avoid this all pagination stuff, by changing the number of results per page and set it to a very high number ... In Knora doc, I find: "The number of results per page is defined in app/v2 in application.conf" <https://docs.knora.org/paradox/03-apis/api-v2/query-language.html>

**Comment by elespdn** [comment]
> you could also make a knoraApiConnection.v2.search.doFulltextSearch per class, in the parameter IFulltextSearchParams there the attribute limitToResourceClass

Yes, seen that. Can be another query box, but this one should be able to look everywhere. If results are well sorted, there is no need for an advanced search neither, that anyway people tend not to use

**Comment by elespdn** [comment]
> Prefer getResources of IRIs instead of several getResource of an IRI to retrieve all your persons and texts.

Thanks, working on it.

**Comment by gfoo** [comment]
> > you should probably manage next page button now before to have more complicated stuffs
> 
> I would like to avoid this all pagination stuff, by changing the number of results per page and set it to a very high number ... In Knora doc, I find: "The number of results per page is defined in app/v2 in application.conf" https://docs.knora.org/paradox/03-apis/api-v2/query-language.html

yes, that's life ! you have to call several times the API by incrementing the `offset` to have more than 25 results.

**Comment by elespdn** [comment]
> From UI point of view I understand that you want to show a lot of informations in your result page but it is not really efficient to call Knora API a lot. A go between way is to show labels and if persons are loaded, then replace label by person name etc. I will show you how to do that.

There is still this point, we'll look at it together then, thanks.

**Pull request merged**
