### PR TITLE
Wip/#41

### PR DESCRIPTION
**Pull request by elespdn**
@gfoo , your opinion would be most welcome here. If you can't, don't worry, I'll figure out something.

I'm trying to work on the publicationTextPage, that is a page that shows bibliographical info about the publication (author, title, date, etc.) plus other stuff.

It is actually the first time I have a link in one of the properties: the class `Publication` has property `publicationHasAuthor` and `publicationHasAuthorValue`, which link to an instance of the class `Author`. Now of course when I retrieve the info about the publication, I don't want the iri of the author, but the author's surname and name, which are properties (`authorHasFamilyName` and `authorHasGivenName`) of the class `Author`.

What I've done to get this information is an asynchronous query: first I ask for the publication, then I ask for the author. See `pub-text-page.component.ts`.

But I'm not sure this is the right way: in this case, I only have one such property to retrieve, but if a class has a lot of link properties, it might become too slow ... no?

Maybe something could be done in `data.service.ts`? I've written the following gravsearch query, but then not sure how to handle the `readRes2PublicationLight` function there below ...

Any hint welcome.

```js
getPublicationLight(iri: string): Observable<PublicationLight[]> {

    const gravsearchQuery = `
PREFIX knora-api: <http://api.knora.org/ontology/knora-api/v2#>
PREFIX roud-oeuvres: <${this.getOntoPrefixPath()}>
CONSTRUCT {
  ?publication knora-api:isMainResource true .
  ?publication roud-oeuvres:publicationHasTitle ?title .
  ?publication roud-oeuvres:publicationHasDate ?date .
} WHERE {
  ${iri} roud-oeuvres:publicationHasTitle ?title .
  ${iri} roud-oeuvres:publicationHasDate ?date .
  ${iri} roud-oeuvres:publicationHasAuthorValue ?authorValue .
  ?authorValue roud-oeuvres:authorHasFamilyName ?authorSurname .
  ?authorValue roud-oeuvres:authorHasGivenName ?authorName .
} 
`;
    return this.knoraApiConnection.v2.search
      .doExtendedSearch(gravsearchQuery)
      .pipe(
        map((readResources: ReadResource[]) =>
          readResources.map(r => this.readRes2PublicationLight(r))
        )
      );
  }
```

Actually this is not a correct gravsearch query, but the corresponding sparql would be:

```sparql
PREFIX roud-oeuvres: <http://www.knora.org/ontology/0112/roud-oeuvres#>
PREFIX knora-base: <http://www.knora.org/ontology/knora-base#>
select ?authorSurname ?authorName ?title ?date 
WHERE {
  <http://rdfh.ch/0112/1jhxvk7rTcCDsVGKiMp2vA> roud-oeuvres:publicationHasTitle ?titleU .
  ?titleU knora-base:valueHasString ?title .
  <http://rdfh.ch/0112/1jhxvk7rTcCDsVGKiMp2vA> roud-oeuvres:publicationHasDate ?dateU .
  ?dateU knora-base:valueHasString ?date .
  <http://rdfh.ch/0112/1jhxvk7rTcCDsVGKiMp2vA> roud-oeuvres:publicationHasAuthor ?authorValue .
  ?authorValue roud-oeuvres:authorHasFamilyName ?authorSurnameU .
  ?authorSurnameU knora-base:valueHasString ?authorSurname .
  ?authorValue roud-oeuvres:authorHasGivenName ?authorNameU .
  ?authorNameU knora-base:valueHasString ?authorName .
}
```

### CODE REVIEW

**Comment by gfoo** [comment]
### General point:

> But I'm not sure this is the right way: in this case, I only have one such property to retrieve, but if a class has a lot of link properties, it might become too slow ... no?

By default, the simple way is: if a resource A depends on B, you have to get A (alone) and from property in A you get the iri of B to then retrieve B.

It is more complicated if A depends on B that depends of C and so on, more the path is long more it is expensive, more complicated is your code. My wrong solution in LL was to retrieve all in same time, bad idea, retrieve to many data blocked the UI and I produced complex code to maintain. You have to sequentially retrieve data because 1/ you will show progressively infos in your page (the user won't have to wait) 2/ you will use Knora API smoothly (to not overload the server with many parallel calls)

### Gravsearch query

> Actually this is not a correct gravsearch query, but the corresponding sparql would be:

Why you want to make a query ? to be efficient ? Right now no so easy to debug your query without any data... But normally it should work, and normally you should have the both resources in `ReadResource`, but where ? you have to dig it with console.log :)
IMHO, when you can, avoid complex query even if it seems more logical to you, the main problem you could face is to not have the `ReadResource` correctly filled with all the resouces you are supposed to get... 


Any way, in your case, for 2 resources the simple way is what I can see in your branch, just get the both resources using  `getResource`, maybe your mistake is how to fill the `authorValue` attribute ?

1. Get Publication resource

So your `getPublicationLight` is correct, you retrieve the resource with `getResource` and in the `authorValue` attribute (I would prefer `authorIRI`) should have the `IRI` of the author. But `getFirstValueAsStringOrNullOfProperty` does not do that (maybe). The IRIs of a property in `ReadResource` is retrieved like that (a piece of code to adapt):
```typescript
getLinkedResIRIsOrNullOfProperty(
    res: ReadResource,
    property: string
  ): string[] {
    const values: string[] = res
      ? res.properties[`${this.ontoPrefix()}${property}`].map(
          o => o["linkedResourceIri"]
        )
      : null;
    return values;
  }
```
And so:
```typescript
authorValue: this.getLinkedResIRIsOrNullOfProperty(
        readResource,
        `${this.getOntoPrefixPath()}publicationHasAuthorValue`
      )[0], // first IRI
```
Log into console the `ReadResource` object to understand where you can find the IRI of linked resources... (maybe the API is now more advanced, this piece of code is from February)

2. Get author resource 

`getAuthorLight` is correct, you get the resource as usual !

**n.b.** : Maybe your are a little bit confused with the `Light` classes ? they are only useful with gravsearch because you retrieve only the props you want, when you use `getResource` this is not a `Light` class, because you get all the props by default!



Let me know if I answered to your question(s) ? 🤔

**Comment by elespdn** [comment]
Hi @gfoo , u are an angel.

> By default, the simple way is: if a resource A depends on B, you have to get A (alone) and from property in A you get the iri of B to then retrieve B.
Yes.

> It is more complicated if A depends on B that depends of C and so on, more the path is long more it is expensive, more complicated is your code. My wrong solution in LL was to retrieve all in same time, bad idea, retrieve too many data blocked the UI and I produced complex code to maintain. You have to sequentially retrieve data because 1/ you will show progressively infos in your page (the user won't have to wait) 2/ you will use Knora API smoothly (to not overload the server with many parallel calls)
Ok.

> Why you want to make a query ? to be efficient ? Right now no so easy to debug your query without any data... But normally it should work, and normally you should have the both resources in ReadResource, but where ? you have to dig it with console.log :) IMHO, when you can, avoid complex query even if it seems more logical to you, the main problem you could face is to not have the ReadResource correctly filled with all the resources you are supposed to get...
Got it.

> Any way, in your case, for 2 resources the simple way is what I can see in your branch, just get the both resources using getResource, maybe your mistake is how to fill the authorValue attribute ?
I was not clear: the code works :) But I was not sure it was the right way to handle the situation.

> n.b. : Maybe your are a little bit confused with the Light classes ? they are only useful with gravsearch because you retrieve only the props you want, when you use getResource this is not a Light class, because you get all the props by default!
I like them! I think I got this class inheritance thing, I used it a lot in the publication.model and it is pretty handy, thanks ;)

> Let me know if I answered to your question(s) ? 
Indeed! You confirmed that it is not wrong, great. This publication page will get more complicated, as I will add new parts. So I might come back to you for an opinion once it is finished. Thanks*

**Comment by elespdn** [comment]
Still to fix:

[ ] genesis part of publication page
[ ] genesis part of ms page
[ ] ms desc

**Comment by elespdn** [comment]
Close this commit here, even if it is not finished. Open new issues for each separate point about publication and ms page.

**Pull request merged**
