### PR TITLE
install and use Knora-ui core module and search module

### PR DESCRIPTION
**Pull request by elespdn**
#9 

Following instructions at https://dasch-swiss.github.io/knora-ui/modules/core/readme

Install dependencies, add to those listed on the page

- @angular/common@8.2.14
- @angular/core@8.2.14
- jquery@1.9.1
- popper.js@^1.16.0
- moment
- hammerjs

For Search, also
- @knora/search
- @angular/cdk
- @angular/materials (to be called from src/style.css: `@import "../node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css";` or 'indigo-pink', the other styles do not render well)
- jdnconvertiblecalendar
- @knora/action
- @knora/viewer
- jdnconvertiblecalendardateadapter
- @angular/flex-layout
- ts-md5

Followed all the steps in install and setup, those should be fine.

--- 

Now to use: I don't seem to be able to retrieve the **parameters for connection**, to be used for example in the gravsearchQuery.

See for example the declaration of prefix in `getPersons`: 

in `data.service.ts` I indicated `PREFIX roud-oeuvres: <${AppInitService.knoraApiConnection}/ontology/0112/roud-oeuvres/v2#>` 
or `PREFIX roud-oeuvres: <${this.knoraApiConnection}/ontology/0112/roud-oeuvres/v2#>`

but becomes (from what I see in the browser) `PREFIX roud-oeuvres: <[object Object]/ontology/0112/roud-oeuvres/v2#>`

instead of `PREFIX roud-oeuvres: <http://0.0.0.0:3333/ontology/0112/roud-oeuvres/v2#>`

even if it is defined in `app-init.service.ts`

I've looked in knora-app, but this knoraApiConnection is only used in app-init.service.ts and in app.module.ts ...

I'm surely missing something! @gfoo , any help is welcome :)

### CODE REVIEW

**Comment by gfoo** [comment]
You have to use `${this.knoraApiConnection}` and not `${AppInitService.knoraApiConnection}`, because you inject `knoraApiConnection` as `private` into the constructor, it is now a an attribute of the class `DataService`, so you can access it using `this`.

Cannot test right now, I have an error on my laptop with `npm install` command...

**Comment by elespdn** [comment]
Yes, I did it yesterday (as mentioned in the above comment) but did not work ... Thanks for clarifying the logic, maybe I have to change something else in this data.service now ...

**Comment by gfoo** [comment]
oh yes, it is a little more bit complicated, you have to inject an other `token` in the constructor to get config values:
```
constructor(
    @Inject(KnoraApiConnectionToken)
    private knoraApiConnection: KnoraApiConnection,
    @Inject(KuiConfigToken)
    private kuiConfig: KuiConfig
  ) {}
```

And then you could use it:
```
getOntoPrefixPath() {
    return `${this.kuiConfig.knora.apiProtocol}://${this.kuiConfig.knora.apiHost}:${this.kuiConfig.knora.apiPort}`;
  }

  getPersons(index: number = 0): Observable<Person[]> {
    const gravsearchQuery = `
PREFIX knora-api: <http://api.knora.org/ontology/knora-api/v2#>
PREFIX roud-oeuvres: <${this.getOntoPrefixPath()}/ontology/0112/roud-oeuvres/v2#>
CONSTRUCT {
 [...]
```

**Comment by elespdn** [comment]
Thanks @gfoo !

Fixed that and search added, I still have to fix `model.person`, I think I need to change something because of the changes in `data.service`, will check.

**Comment by gfoo** [comment]
> I still have to fix model.person, I think I need to change something because of the changes in data.service, will check.

yes, there are extra `http://` in `person.model.ts`

**Comment by elespdn** [comment]
yes, there are extra http:// in person.model.ts

> yes, there are extra `http://` in `person.model.ts`

Yes :) Fixed now.

**Comment by gfoo** [comment]
Finally not very happy of my `href` fix on the fly way because, as I thought at the beginning, we bypass the router, so when we click on the link, the app is reloaded!

So, the other way is to listen to `a`'s click `event` and to use the router to navigate to the IRI, smthg like that, I will epxlain to you next time:
```typescript
  onClick(event) {
    this.router.navigate(['resources', event.target.getAttribute('href')]);
    event.preventDefault();
  }

  reRouteLink(el: ElementRef) {
    el.nativeElement.querySelectorAll('a').forEach((aElt: HTMLElement) => {
      aElt.addEventListener('click', this.onClick.bind(this));
    });
  }

```

**Comment by gfoo** [comment]
About the angular lifecycle event to detect if the view changes, we can use `DoCheck`:

```typescript
export class ResourceLinkDirective implements DoCheck {

...

ngDoCheck(): void {
    this.reRouteLink(this.el); // use function, that is defined below
}

...

```

**Comment by gfoo** [comment]
next in #22

**Pull request closed without merging**
